server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: HLAIANavigationBar
  config:
    import: "optional:file:./.env[.properties]"
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
